name: "Run ECS task"
description: "Run task in context of a service"
inputs:
  cluster:
    description: "ECS cluster to run task in"
    required: true
  service:
    description: "ECS service to read parameters from"
    required: true
  task_definition:
    description: "ECS task definition ARN"
    required: false
  command:
    description: "Task command"
    required: true
  show_raw_output:
    description: "Wait for task to complete and display output from task"
    default: false

outputs:
  console_url:
    description: "URL of task page in AWS console"
  raw_output:
    description: "Raw output from task"

runs:
  using: "node12"
  main: "dist/index.js"
