name: "Run ECS task"
description: "Run task in context of a service"
inputs:
  cluster:
    description: "ECS cluster to run task in"
    required: true
  service:
    description: "ECS service to read parameters from"
    required: true
  command:
    description: "Task command"
    required: true
outputs:
  console_url:
    description: "URL of task page in AWS console"
runs:
  using: "node12"
  main: "index.js"
